/**
 * generated by Xtext 2.40.0
 */
package org.xtext.example.resume.resume.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.resume.resume.Customization;
import org.xtext.example.resume.resume.ResumePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Customization</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.resume.resume.impl.CustomizationImpl#getLanguage <em>Language</em>}</li>
 *   <li>{@link org.xtext.example.resume.resume.impl.CustomizationImpl#getJobOfferPath <em>Job Offer Path</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CustomizationImpl extends MinimalEObjectImpl.Container implements Customization
{
  /**
   * The default value of the '{@link #getLanguage() <em>Language</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLanguage()
   * @generated
   * @ordered
   */
  protected static final String LANGUAGE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLanguage() <em>Language</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLanguage()
   * @generated
   * @ordered
   */
  protected String language = LANGUAGE_EDEFAULT;

  /**
   * The default value of the '{@link #getJobOfferPath() <em>Job Offer Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJobOfferPath()
   * @generated
   * @ordered
   */
  protected static final String JOB_OFFER_PATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getJobOfferPath() <em>Job Offer Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJobOfferPath()
   * @generated
   * @ordered
   */
  protected String jobOfferPath = JOB_OFFER_PATH_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CustomizationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ResumePackage.Literals.CUSTOMIZATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLanguage()
  {
    return language;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLanguage(String newLanguage)
  {
    String oldLanguage = language;
    language = newLanguage;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumePackage.CUSTOMIZATION__LANGUAGE, oldLanguage, language));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getJobOfferPath()
  {
    return jobOfferPath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJobOfferPath(String newJobOfferPath)
  {
    String oldJobOfferPath = jobOfferPath;
    jobOfferPath = newJobOfferPath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ResumePackage.CUSTOMIZATION__JOB_OFFER_PATH, oldJobOfferPath, jobOfferPath));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ResumePackage.CUSTOMIZATION__LANGUAGE:
        return getLanguage();
      case ResumePackage.CUSTOMIZATION__JOB_OFFER_PATH:
        return getJobOfferPath();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ResumePackage.CUSTOMIZATION__LANGUAGE:
        setLanguage((String)newValue);
        return;
      case ResumePackage.CUSTOMIZATION__JOB_OFFER_PATH:
        setJobOfferPath((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ResumePackage.CUSTOMIZATION__LANGUAGE:
        setLanguage(LANGUAGE_EDEFAULT);
        return;
      case ResumePackage.CUSTOMIZATION__JOB_OFFER_PATH:
        setJobOfferPath(JOB_OFFER_PATH_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ResumePackage.CUSTOMIZATION__LANGUAGE:
        return LANGUAGE_EDEFAULT == null ? language != null : !LANGUAGE_EDEFAULT.equals(language);
      case ResumePackage.CUSTOMIZATION__JOB_OFFER_PATH:
        return JOB_OFFER_PATH_EDEFAULT == null ? jobOfferPath != null : !JOB_OFFER_PATH_EDEFAULT.equals(jobOfferPath);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (language: ");
    result.append(language);
    result.append(", jobOfferPath: ");
    result.append(jobOfferPath);
    result.append(')');
    return result.toString();
  }

} //CustomizationImpl
